#!/usr/bin/env sh
# bootstrap script
# run this to generate the configure script and other files needed
# by the build system (e.g. source files to compile).

set -e

# Make sure we're in the right directory
if [ ! -f "configure.ac" ]; then
    echo "Error: configure.ac not found. Run this script from the project root directory."
    exit 1
fi

########################################

echo "Generating source file list..."
SOURCES_FILE="src/Makefile.sources"
mkdir -p "$(dirname "$SOURCES_FILE")"

cat > "$SOURCES_FILE" << EOF
# Automatically generated by autogen.sh - DO NOT EDIT
McOsu_SOURCES = \\
EOF

find src -type f '(' -name "*.cpp" -o -name "*.c" ')' | LC_ALL=C sort | \
    sed 's/$/\\/' | \
    sed 's/^/\t/' >> "$SOURCES_FILE"

echo "\$(NULL)" >> "$SOURCES_FILE"

########################################

check_tool() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Error: $1 not found. Please install $2."
        exit 1
    fi
}

check_tool "aclocal" "automake"
check_tool "automake" "automake"
check_tool "autoconf" "autoconf"
check_tool "pkg-config" "pkg-config"

echo "Running autotools..."
autoreconf -fiv

echo "
Bootstrap complete. You can now run:
  ./configure [options]
  make
  make install

Some configure options:
  --prefix=/usr           Install to /usr instead of ./dist
  --enable-debug          Enable debug build
  --disable-native        Disable native CPU optimizations
  --disable-system-deps   Build some dependencies from source
  --enable-static         Try to build/link libraries statically
  --enable-lto            Enable link-time optimization (default: used if available)

For a full list of options, run: ./configure --help
"
