//================ Copyright (c) 2015, PG, All rights reserved. =================//
//
// Purpose:		vk defs
//
// $NoKeywords: $vk $os
//===============================================================================//

#pragma once
#ifndef KEYBOARDKEYS_H
#define KEYBOARDKEYS_H

#include <SDL3/SDL.h>

// alphabet
#define KEY_A				SDL_SCANCODE_A
#define KEY_B				SDL_SCANCODE_B
#define KEY_C				SDL_SCANCODE_C
#define KEY_D				SDL_SCANCODE_D
#define KEY_E				SDL_SCANCODE_E
#define KEY_F				SDL_SCANCODE_F
#define KEY_G				SDL_SCANCODE_G
#define KEY_H				SDL_SCANCODE_H
#define KEY_I				SDL_SCANCODE_I
#define KEY_J				SDL_SCANCODE_J
#define KEY_K				SDL_SCANCODE_K
#define KEY_L				SDL_SCANCODE_L
#define KEY_M				SDL_SCANCODE_M
#define KEY_N				SDL_SCANCODE_N
#define KEY_O				SDL_SCANCODE_O
#define KEY_P				SDL_SCANCODE_P
#define KEY_Q				SDL_SCANCODE_Q
#define KEY_R				SDL_SCANCODE_R
#define KEY_S				SDL_SCANCODE_S
#define KEY_T				SDL_SCANCODE_T
#define KEY_U				SDL_SCANCODE_U
#define KEY_V				SDL_SCANCODE_V
#define KEY_W				SDL_SCANCODE_W
#define KEY_X				SDL_SCANCODE_X
#define KEY_Y				SDL_SCANCODE_Y
#define KEY_Z				SDL_SCANCODE_Z

// numbers
#define KEY_0				SDL_SCANCODE_0
#define KEY_1				SDL_SCANCODE_1
#define KEY_2				SDL_SCANCODE_2
#define KEY_3				SDL_SCANCODE_3
#define KEY_4				SDL_SCANCODE_4
#define KEY_5				SDL_SCANCODE_5
#define KEY_6				SDL_SCANCODE_6
#define KEY_7				SDL_SCANCODE_7
#define KEY_8				SDL_SCANCODE_8
#define KEY_9				SDL_SCANCODE_9

// numpad
#define KEY_NUMPAD0			SDL_SCANCODE_KP_0
#define KEY_NUMPAD1			SDL_SCANCODE_KP_1
#define KEY_NUMPAD2			SDL_SCANCODE_KP_2
#define KEY_NUMPAD3			SDL_SCANCODE_KP_3
#define KEY_NUMPAD4			SDL_SCANCODE_KP_4
#define KEY_NUMPAD5			SDL_SCANCODE_KP_5
#define KEY_NUMPAD6			SDL_SCANCODE_KP_6
#define KEY_NUMPAD7			SDL_SCANCODE_KP_7
#define KEY_NUMPAD8			SDL_SCANCODE_KP_8
#define KEY_NUMPAD9			SDL_SCANCODE_KP_9
#define KEY_MULTIPLY		SDL_SCANCODE_KP_MULTIPLY
#define KEY_ADD				SDL_SCANCODE_KP_PLUS
#define KEY_SEPARATOR		SDL_SCANCODE_KP_EQUALS
#define KEY_SUBTRACT		SDL_SCANCODE_KP_MINUS
#define KEY_DECIMAL			SDL_SCANCODE_KP_DECIMAL
#define KEY_DIVIDE			SDL_SCANCODE_KP_DIVIDE

// function keys
#define KEY_F1				SDL_SCANCODE_F1
#define KEY_F2				SDL_SCANCODE_F2
#define KEY_F3				SDL_SCANCODE_F3
#define KEY_F4				SDL_SCANCODE_F4
#define KEY_F5				SDL_SCANCODE_F5
#define KEY_F6				SDL_SCANCODE_F6
#define KEY_F7				SDL_SCANCODE_F7
#define KEY_F8				SDL_SCANCODE_F8
#define KEY_F9				SDL_SCANCODE_F9
#define KEY_F10				SDL_SCANCODE_F10
#define KEY_F11				SDL_SCANCODE_F11
#define KEY_F12				SDL_SCANCODE_F12

// arrow keys
#define KEY_LEFT			SDL_SCANCODE_LEFT
#define KEY_RIGHT			SDL_SCANCODE_RIGHT
#define KEY_UP				SDL_SCANCODE_UP
#define KEY_DOWN			SDL_SCANCODE_DOWN

// special keys
#define KEY_TAB				SDL_SCANCODE_TAB
#define KEY_NUMPAD_ENTER	SDL_SCANCODE_KP_ENTER
#define KEY_ENTER			SDL_SCANCODE_RETURN
#define KEY_LSHIFT			SDL_SCANCODE_LSHIFT
#define KEY_RSHIFT			SDL_SCANCODE_RSHIFT
#define KEY_LCONTROL		SDL_SCANCODE_LCTRL
#define KEY_RCONTROL		SDL_SCANCODE_RCTRL
#define KEY_LALT			SDL_SCANCODE_LALT
#define KEY_RALT			SDL_SCANCODE_RALT
#define KEY_ESCAPE			SDL_SCANCODE_ESCAPE
#define KEY_TILDE			SDL_SCANCODE_GRAVE
#define KEY_SPACE			SDL_SCANCODE_SPACE
#define KEY_BACKSPACE		SDL_SCANCODE_BACKSPACE
#define KEY_END				SDL_SCANCODE_END
#define KEY_INSERT			SDL_SCANCODE_INSERT
#define KEY_DELETE			SDL_SCANCODE_DELETE
#define KEY_HELP			SDL_SCANCODE_HELP
#define KEY_HOME			SDL_SCANCODE_HOME
#define KEY_LSUPER			SDL_SCANCODE_LGUI
#define KEY_RSUPER			SDL_SCANCODE_RGUI
#define KEY_PAGEUP			SDL_SCANCODE_PAGEUP
#define KEY_PAGEDOWN		SDL_SCANCODE_PAGEDOWN

#endif
