//================ Copyright (c) 2025, WH, All rights reserved. =================//
//
// Purpose:		base class for UI elements to inherit from, app-wide
//
// $NoKeywords: $osuui
//===============================================================================//

#pragma once

#include "CBaseUIElement.h"

#include "CBaseUICheckbox.h"
#include "CBaseUIContainer.h"
#include "CBaseUILabel.h"
#include "CBaseUIScrollView.h"
#include "CBaseUITextbox.h"

class OsuUIElement : public CBaseUIElement
{
public:
	using CBaseUIElement::CBaseUIElement;

	enum elemTypeOsu : TypeId // WIP
	{
		OPTIONSSKINPREVIEW = APP_TYPES_START,
		OPTIONSSLIDERPREVIEW,
		UICONTEXTMENU,
		RANKINGSCREENINFOLABEL,
		SEARCHOVERLAY,
		CUSTOMCHANGELOGLABELLABELBUTTON,
		MAINMENUPAUSEBUTTON,
		MAINMENUMAINBUTTON,
		MAINMENUBUTTON,
		MODSELECTOROVERRIDESLIDERDESCBUTTON,
		MODSELECTOROVERRIDESLIDERLOCKBUTTONCHECKBOX,
		OPTIONSMENUKEYBINDLABELLABEL,
		OPTIONSMENUCATEGORYBUTTON,
		OPTIONSMENURESETBUTTON,
		OPTIONSMENUKEYBINDBUTTON,
		RANKINGSCREENINDEXLABELLABEL,
		RANKINGSCREENBOTTOMELEMENTLABEL,
		RANKINGSCREENSCROLLDOWNINFOBUTTON,
		UISONGBROWSERNORECORDSSETELEMENTLABEL,
		UIBACKBUTTON,
		OSUUIBUTTON,
		OSUUISLIDER,
		UICHECKBOXCHECKBOX,
		UICONTEXTMENUBUTTON,
		UICONTEXTMENUTEXTBOXTEXTBOX,
		UIMODSELECTORMODBUTTON,
		UIPAUSEMENUBUTTON,
		UIRANKINGSCREENRANKINGPANELIMAGE,
		UISELECTIONBUTTON,
		UISONGBROWSERBUTTON,
		UISONGBROWSERSONGBUTTON,
		UISONGBROWSERCOLLECTIONBUTTON,
		UISONGBROWSERDIFFICULTYBUTTON,
		UISONGBROWSERINFOLABELBUTTON,
		UISONGBROWSERSCOREBUTTON,
		UISONGBROWSERUSERBUTTON,
		UIUSERSTATSSCREENLABELLABEL,
		UIVOLUMESLIDER,
		USERSTATSSCREENMENUBUTTON,
		OSU_UI_ELEMENT_END
	};
};
