name: linux-multiarch
on:
  push:
    branches:
      - main
      - dev2
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x32]
        include:
          - arch: x64
            host: x86_64-pc-linux-gnu
          - arch: x32
            host: i686-pc-linux-gnu
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          driver: docker

      - name: Set up build directory
        run: |
          mkdir -p "$(pwd)"/build
          mkdir -p "$(pwd)"/.ccache

      - name: ccache
        uses: actions/cache@v4
        with:
          path: ./.ccache
          key: ccache-linux-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ccache-linux-${{ matrix.arch }}-

      - name: Build McOsu-ng with Docker
        run: |
          docker buildx build --progress=plain \
          -f .github/workflows/docker/Dockerfile \
          -t mcosu-ng-builder .
          docker run --rm \
            -e HOST=${{ matrix.host }} \
            -e CCACHE_DIR=/ccache \
            --mount type=bind,source="$(pwd)"/build,target=/build \
            --mount type=bind,source="$(pwd)",target=/src,readonly \
            --mount type=bind,source="$(pwd)"/.ccache,target=/ccache \
            mcosu-ng-builder

      - uses: actions/upload-artifact@v4
        with:
          name: mcosu-ng-linux-${{ matrix.arch }}
          path: ./build/dist
