name: linux-x64
on:
  push:
    branches:
      - main
      - dev2
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          driver: docker

      - name: Set up build directory
        run: |
          mkdir -p "$(pwd)"/build
          
      - name: Build McOsu-ng with Docker
        run: |
          docker buildx build --progress=plain \
          -f .github/workflows/docker/Dockerfile \
          -t mcosu-ng-builder .

          docker run --rm \
            -e HOST=x86_64-pc-linux-gnu \
            --mount type=bind,source="$(pwd)"/build,target=/build \
            --mount type=bind,source="$(pwd)",target=/src,readonly \
            mcosu-ng-builder
          
      - uses: actions/upload-artifact@v4
        with:
          name: mcosu-ng-linux-x64
          path: ./build/dist