name: win-x64
on:
  push:
    branches:
      - main
      - dev2
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
          
      - name: Installing dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel libx11 libxi glu \
                      glew libjpeg-turbo libglvnd freetype2 sdl3 zlib wget \
                      cmake meson nasm git autoconf automake libtool autoconf-archive \
                      mingw-w64-gcc
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R user: .
          chown -R user: . /tmp
          cd ..
      
      - name: Building McOsu-ng
        run: |
          autoreconf
          ./configure --disable-system-deps --enable-static --disable-native --host=x86_64-w64-mingw32
          make -j$(nproc) install
      
      - uses: actions/upload-artifact@v4
        with:
          name: mcosu-ng-win-x64
          path: ./dist
